spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.178.7/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=fVGEcE75x6gJpQHe9H2GLow7
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:780z6LHxPQsGoTP2STlNiGWB@172.21.204.57/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 

